CREATE TABLE IF NOT EXISTS users
(
    user_id             BIGINT GENERATED BY DEFAULT AS IDENTITY     NOT NULL,
    name                VARCHAR(255)                                NOT NULL,
    email               VARCHAR(320)                                NOT NULL UNIQUE,
    CONSTRAINT pk_user PRIMARY KEY (user_id)
);

CREATE TABLE IF NOT EXISTS categories
(
    category_id         BIGINT GENERATED BY DEFAULT AS IDENTITY     NOT NULL,
    name                VARCHAR(255)                                NOT NULL UNIQUE,
    CONSTRAINT pk_category PRIMARY KEY (category_id)
);

CREATE TABLE IF NOT EXISTS compilations
(
    compilation_id      BIGINT GENERATED BY DEFAULT AS IDENTITY     NOT NULL,
    title               VARCHAR(512)                                NOT NULL UNIQUE,
    pinned              BOOLEAN DEFAULT FALSE,
    CONSTRAINT pk_compilation PRIMARY KEY (compilation_id)
);

CREATE TABLE IF NOT EXISTS events
(
    event_id            BIGINT GENERATED BY DEFAULT AS IDENTITY     NOT NULL,
    annotation          VARCHAR(2000)                               NOT NULL,
    title               VARCHAR(120)                                NOT NULL,
    description         VARCHAR(7000)                               NOT NULL,
    state               VARCHAR(15) DEFAULT 'PENDING',
    created             TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(),
    published           TIMESTAMP WITHOUT TIME ZONE,
    start_date          TIMESTAMP WITHOUT TIME ZONE                 NOT NULL,
    initiator_id        INTEGER                                     NOT NULL,
    lat                 FLOAT                                       NOT NULL,
    lon                 FLOAT                                       NOT NULL,
    category_id         INTEGER                                     NOT NULL,
    paid                BOOLEAN DEFAULT FALSE,
    request_Moderation  BOOLEAN DEFAULT FALSE,
    participant_limit   INTEGER DEFAULT 0,
    CONSTRAINT pk_event PRIMARY KEY (event_id),
    CONSTRAINT fk_initiator FOREIGN KEY (initiator_id) REFERENCES users (user_id) ON DELETE CASCADE,
    CONSTRAINT fk_category FOREIGN KEY (category_id) REFERENCES categories (category_id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS requests
(
    request_id          BIGINT GENERATED BY DEFAULT AS IDENTITY     NOT NULL,
    event_id            INTEGER                                     NOT NULL,
    user_id             INTEGER                                     NOT NULL,
    status              VARCHAR(15) DEFAULT 'PENDING',
    created             TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(),
    CONSTRAINT pk_request PRIMARY KEY (request_id),
    CONSTRAINT fk_event_request FOREIGN KEY (event_id) REFERENCES events (event_id) ON DELETE CASCADE,
    CONSTRAINT fk_user_request FOREIGN KEY (user_id) REFERENCES users (user_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS events_compilations
(
    event_compilation_id BIGINT GENERATED BY DEFAULT AS IDENTITY    NOT NULL,
    event_id             INTEGER                                    NOT NULL,
    compilation_id       INTEGER                                    NOT NULL,
    CONSTRAINT fk_compilation_event FOREIGN KEY (event_id) REFERENCES events (event_id) ON DELETE CASCADE,
    CONSTRAINT fk_event_compilation FOREIGN KEY (compilation_id) REFERENCES compilations (compilation_id) ON DELETE CASCADE
);

