CREATE TABLE IF NOT EXISTS stats
(
    id      INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    app     VARCHAR(20)                          NOT NULL,
    uri     VARCHAR(20)                          NOT NULL,
    ip      VARCHAR(15)                          NOT NULL,
    created TIMESTAMP WITHOUT TIME ZONE          NOT NULL,
    CONSTRAINT pk_stats PRIMARY KEY (id)
);